spring:
  datasource:
    hikari:
      connectionTimeout: 15000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/accountant
    username: postgres
    password: SLAwek1!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        #        use_sql_comments: true
        #        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jooq:
    sql-dialect: POSTGRES
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 30MB
  main:
    banner-mode: off
  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher

go-cardless:
  service-url: https://bankaccountdata.gocardless.com/api/v2/

cron:
  fetch-accounts: "*/10 * * * * *"
  fetch-accounts-monthly: "*/10 * * * * *"
  fetch-transactions: "*/10 * * * * *"